# Generated by Django 3.1.1 on 2020-10-18 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='maid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('name', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=3)),
                ('phone', models.CharField(max_length=10)),
                ('detail', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('skill', models.CharField(max_length=255)),
                ('review', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='statusmaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('maid_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maid.maid')),
            ],
        ),
        migrations.CreateModel(
            name='historymaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maid.maid')),
            ],
        ),
    ]
