# Generated by Django 3.1.1 on 2020-10-12 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maid',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.CreateModel(
            name='statusmaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('maid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maid.maid')),
            ],
        ),
    ]
