# Generated by Django 3.1.1 on 2020-10-27 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historymaid',
            old_name='maid',
            new_name='maid_history',
        ),
    ]
