# Generated by Django 3.1.1 on 2020-10-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0002_auto_20201006_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Image'),
        ),
    ]
