# Generated by Django 3.1.1 on 2020-10-12 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0002_auto_20201012_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='historymaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maid.maid')),
            ],
        ),
    ]
