# Generated by Django 3.1.1 on 2020-10-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0003_auto_20201006_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maid',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
