# Generated by Django 3.1.1 on 2020-10-14 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0003_historymaid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusmaid',
            old_name='maid',
            new_name='maid_name',
        ),
    ]
